from __future__ import annotations

# Generated from the old project defaultConfig. Persistent config is stored in SQLite.
DEFAULT_SUBMISSION_CONFIG = {'botToken': '',
 'telegramApi': {'apiId': '', 'apiHash': '', 'session': ''},
 'tmdbToken': '',
 'tmdbLanguage': 'zh-CN',
 'system': {'appPassword': ''},
 'allowedUserIds': [],
 'channels': [{'id': 'private', 'title': '私有', 'chatId': '', 'enabled': True, 'isDefault': True, 'role': 'private'}],
 'routing': {'publicReleaseGroups': [],
             'releaseGroupChannelId': 'private',
             'noReleaseGroupCompletedChannelId': '',
             'noReleaseGroupUpdatingChannelId': '',
             'fallbackChannelId': ''},
 'recognitionRules': [{'id': 'season_episode',
                       'name': '季集',
                       'enabled': True,
                       'pattern': '(?:^|[\\s._\\-\\[\\]()])(?<seasonEpisode>S\\d{1,2}(?:(?:E|EP)\\d{1,4}(?:(?:E|EP)\\d{1,4}|\\s*[-~]\\s*(?:S\\d{1,2})?(?:E|EP)?\\d{1,4})?|\\s*[-~]\\s*S\\d{1,2})?|(?:EP|Episode)\\s*\\d{1,4}(?:\\s*[-~]\\s*(?:EP)?\\d{1,4})?|第\\s*\\d{1,4}\\s*集)(?=$|[\\s._\\-\\[\\]()])',
                       'flags': 'iu'},
                      {'id': 'tmdbid',
                       'name': 'TMDB ID',
                       'enabled': True,
                       'pattern': '(?:tmdbid|tmdb)[=\\-_: ](?<tmdbId>\\d{2,10})',
                       'flags': 'i'},
                      {'id': 'title_year',
                       'name': '标题年份',
                       'enabled': True,
                       'pattern': '(?<title>[\\p{Script=Han}A-Za-z0-9][^\\n\\r/\\\\]{1,100}?)\\s*[\\(（](?<year>19\\d{2}|20\\d{2})[\\)）]',
                       'flags': 'iu'},
                      {'id': 'quality',
                       'name': '画质',
                       'enabled': True,
                       'pattern': '(?:^|[\\s._\\-\\[\\]()])(?<quality>8K|6K|5K|4K|2K|UHD|QHD|FHD|(?<!DTS[-.])(?<!Ultra[\\s._-])HD|4320p|3160p|3072p|2880p|2160p|1440p|1080p|1080i|720p|576p|540p|480p|360p)(?=$|[\\s._\\-\\[\\]()])',
                       'flags': 'i'},
                      {'id': 'resource_type',
                       'name': '资源类型',
                       'enabled': True,
                       'pattern': '(?:^|[\\s._\\-\\[\\]()])(?<resourceType>REMUX|(?:UHD|Ultra\\s?HD)[\\s._-]*Blu[- '
                                  '.]?Ray|UHDTV|Blu[- .]?Ray|WEB[- '
                                  '.]?DL|WEBRip|HDTV|DVDRip|BDRip|HDRip|HDTC|CAM|TS)(?=$|[\\s._\\-\\[\\]()])',
                       'flags': 'i'},
                      {'id': 'source',
                       'name': '片源',
                       'enabled': True,
                       'pattern': '(?:^|[\\s._\\-\\[\\]()])(?<source>WEB[- '
                                  '.]?DL|WEBRip|(?:UHD|Ultra\\s?HD)[\\s._-]*Blu[- .]?Ray|UHDTV|Blu[- '
                                  '.]?Ray|BDRip|HDRip|HDTV|REMUX)(?=$|[\\s._\\-\\[\\]()])',
                       'flags': 'i'},
                      {'id': 'web_source',
                       'name': '流媒体平台',
                       'enabled': True,
                       'pattern': '(?:^|[\\s._\\-\\[\\]()])(?<webSource>AMZN|Amazon|Prime|NF|Netflix|ATVP|AppleTV\\+|Apple\\s?TV\\+|iT|iTunes|DSNP|Disney\\+|Disney\\s?Plus|Hulu|HMAX|MAX|HBOGO|HBO|CR|Crunchyroll|IQ|iQIYI|WeTV|Bilibili|B-Global|BG|ABEMA|ABMA|ADN|AT-X|Baha|FOD|FriDay|Friday影音|FUNi|Funimation|HIDI|HIDIVE|UNXT|U-Next|VIU|LINETV|Hami|HamiVideo|MW|CATCHPLAY|CPP|YT|YouTube)(?=$|[\\s._\\-\\[\\]()])',
                       'flags': 'i'},
                      {'id': 'effect',
                       'name': '特效/HDR',
                       'enabled': True,
                       'pattern': '(?:^|[\\s._\\-\\[\\]()])(?<effect>Dolby\\s?Vision|DoVi|DV|HDR10\\+?|HDR\\s?Vivid|HDRVivid|Vivid|EDR|HQ|HLG|SDR|HDR|3D)(?=$|[\\s._\\-\\[\\]()])',
                       'flags': 'i'},
                      {'id': 'video_codec',
                       'name': '视频编码',
                       'enabled': True,
                       'pattern': '(?<videoCodec>AV1|AVC|HEVC|H[. ]?265|X[. ]?265|H[. ]?264|X[. ]?264|MPEG-?2|VC-?1)',
                       'flags': 'i'},
                      {'id': 'video_bit',
                       'name': '位深',
                       'enabled': True,
                       'pattern': '(?<videoBit>8\\s?bit|10\\s?bit|12\\s?bit)',
                       'flags': 'i'},
                      {'id': 'audio_codec',
                       'name': '音频编码',
                       'enabled': True,
                       'pattern': '(?<audioCodec>TrueHD(?:[.\\s-]*(?:Dolby[.\\s-]*)?Atmos)?(?:[.\\s-]*\\d\\.\\d)?|DDP[.\\s-]?\\d\\.\\d(?:[.\\s-]?(?:Atmos|JOC))?|DD\\+?[.\\s-]?\\d\\.\\d(?:[.\\s-]?(?:Atmos|JOC))?|DTS[- '
                                  '.]?HD(?:[- .]?MA|[- .]?HRA)?(?:[.\\s-]?\\d\\.\\d)?|DTS[- '
                                  '.]?X(?:[.\\s-]?\\d\\.\\d)?|DTS(?:[.\\s-]?\\d\\.\\d)?|AAC(?:[.\\s-]?\\d\\.\\d)?|FLAC(?:[.\\s-]?\\d\\.\\d)?|LPCM(?:[.\\s-]?\\d\\.\\d)?|PCM(?:[.\\s-]?\\d\\.\\d)?|AC3(?:[.\\s-]?\\d\\.\\d)?|EAC3(?:[.\\s-]?\\d\\.\\d)?|Opus(?:[.\\s-]?\\d\\.\\d)?|AV3A(?:[.\\s-]?\\d\\.\\d)?|\\d{1,2}\\s*(?:Audios?|AudioTracks?|Audio\\s*Tracks?|Audio|音轨|聲軌|声轨))',
                       'flags': 'i'},
                      {'id': 'fps',
                       'name': '帧率',
                       'enabled': True,
                       'pattern': '(?:^|[\\s._\\-\\[\\]()])(?<fps>(?<!H\\.)(?<!X\\.)(?<!H)(?<!X)\\d{2,3}(?:\\.\\d{1,3})?\\s?fps)(?=$|[\\s._\\-\\[\\]()])',
                       'flags': 'i'},
                      {'id': 'size',
                       'name': '大小',
                       'enabled': True,
                       'pattern': '(?:^|[^A-Za-z0-9])(?<size>\\d+(?:\\.\\d+)?\\s*(?:TB|GB|MB))(?![A-Za-z0-9])',
                       'flags': 'i'},
                      {'id': 'release_group_suffix',
                       'name': '发布组尾缀',
                       'enabled': True,
                       'pattern': '-(?<releaseGroup>[\\p{Script=Han}A-Za-z0-9][\\p{Script=Han}A-Za-z0-9@-]{1,40})(?:\\.(?:mkv|mp4|avi|mov|wmv|flv|webm|m4v|mpeg|mpg|3gp|ts|m2ts|mts))?$',
                       'flags': 'imu'}],
 'ruleConfig': {'quality': [{'id': 'quality_4320p',
                             'enabled': True,
                             'value': '4320p',
                             'aliases': ['4320p'],
                             'rank': '4320',
                             'order': 80,
                             'priority': 3},
                            {'id': 'quality_8k',
                             'enabled': True,
                             'value': '8K',
                             'aliases': ['8K'],
                             'rank': '4320',
                             'order': 80,
                             'priority': 2},
                            {'id': 'quality_3160p',
                             'enabled': True,
                             'value': '3160p',
                             'aliases': ['3160p'],
                             'rank': '3160',
                             'order': 70,
                             'priority': 3},
                            {'id': 'quality_6k',
                             'enabled': True,
                             'value': '6K',
                             'aliases': ['6K', '3072p'],
                             'rank': '3160',
                             'order': 70,
                             'priority': 2},
                            {'id': 'quality_2880p',
                             'enabled': True,
                             'value': '2880p',
                             'aliases': ['2880p'],
                             'rank': '2880',
                             'order': 60,
                             'priority': 3},
                            {'id': 'quality_5k',
                             'enabled': True,
                             'value': '5K',
                             'aliases': ['5K'],
                             'rank': '2880',
                             'order': 60,
                             'priority': 2},
                            {'id': 'quality_2160p',
                             'enabled': True,
                             'value': '2160p',
                             'aliases': ['2160p', '4K', 'UHD', 'Ultra HD', 'UltraHD', 'Ultra-HD'],
                             'rank': '2160',
                             'order': 50,
                             'priority': 3},
                            {'id': 'quality_1440p',
                             'enabled': True,
                             'value': '1440p',
                             'aliases': ['1440p'],
                             'rank': '1440',
                             'order': 40,
                             'priority': 3},
                            {'id': 'quality_2k',
                             'enabled': True,
                             'value': '2K',
                             'aliases': ['2K', 'QHD'],
                             'rank': '1440',
                             'order': 40,
                             'priority': 2},
                            {'id': 'quality_1080p',
                             'enabled': True,
                             'value': '1080P',
                             'aliases': ['1080p', 'FHD'],
                             'rank': '1080',
                             'order': 30,
                             'priority': 3},
                            {'id': 'quality_1080i',
                             'enabled': True,
                             'value': '1080I',
                             'aliases': ['1080i'],
                             'rank': '1080I',
                             'order': 31,
                             'priority': 3},
                            {'id': 'quality_720p',
                             'enabled': True,
                             'value': '720P',
                             'aliases': ['720p', 'HD'],
                             'rank': '720',
                             'order': 20,
                             'priority': 3},
                            {'id': 'quality_576p',
                             'enabled': True,
                             'value': '576P',
                             'aliases': ['576p'],
                             'rank': '576',
                             'order': 15,
                             'priority': 1},
                            {'id': 'quality_540p',
                             'enabled': True,
                             'value': '540P',
                             'aliases': ['540p'],
                             'rank': '540',
                             'order': 14,
                             'priority': 1},
                            {'id': 'quality_480p',
                             'enabled': True,
                             'value': '480P',
                             'aliases': ['480p'],
                             'rank': '480',
                             'order': 10,
                             'priority': 1},
                            {'id': 'quality_360p',
                             'enabled': True,
                             'value': '360P',
                             'aliases': ['360p'],
                             'rank': '360',
                             'order': 5,
                             'priority': 1}],
                'source': [{'id': 'source_uhd_bluray_remux',
                            'enabled': True,
                            'value': 'UHD BluRay Remux',
                            'aliases': ['UHD BluRay Remux', 'Ultra HD BluRay Remux', 'UHD Blu-ray Remux'],
                            'order': 110},
                           {'id': 'source_bluray_remux',
                            'enabled': True,
                            'value': 'BluRay Remux',
                            'aliases': ['BluRay Remux', 'Blu-ray Remux', 'BD Remux'],
                            'order': 105},
                           {'id': 'source_uhd_bluray',
                            'enabled': True,
                            'value': 'UHD BluRay',
                            'aliases': ['UHD BluRay', 'Ultra HD BluRay', 'UHD Blu-ray'],
                            'order': 100},
                           {'id': 'source_remux',
                            'enabled': True,
                            'value': 'Remux',
                            'aliases': ['Remux', 'REMUX'],
                            'order': 95},
                           {'id': 'source_bluray',
                            'enabled': True,
                            'value': 'BluRay',
                            'aliases': ['BluRay', 'Blu-ray', 'BD'],
                            'order': 90},
                           {'id': 'source_webdl',
                            'enabled': True,
                            'value': 'WEB-DL',
                            'aliases': ['WEB-DL', 'WEBDL', 'WEB DL'],
                            'order': 80},
                           {'id': 'source_webrip',
                            'enabled': True,
                            'value': 'WEBRip',
                            'aliases': ['WEBRip', 'WEB-Rip', 'WEB Rip'],
                            'order': 75},
                           {'id': 'source_uhdtv', 'enabled': True, 'value': 'UHDTV', 'aliases': ['UHDTV'], 'order': 70},
                           {'id': 'source_hdtv', 'enabled': True, 'value': 'HDTV', 'aliases': ['HDTV'], 'order': 60},
                           {'id': 'source_bdrip', 'enabled': True, 'value': 'BDRip', 'aliases': ['BDRip'], 'order': 50},
                           {'id': 'source_hdrip', 'enabled': True, 'value': 'HDRip', 'aliases': ['HDRip'], 'order': 45},
                           {'id': 'source_dvdrip',
                            'enabled': True,
                            'value': 'DVDRip',
                            'aliases': ['DVDRip'],
                            'order': 40},
                           {'id': 'source_hdtc', 'enabled': True, 'value': 'HDTC', 'aliases': ['HDTC'], 'order': 30},
                           {'id': 'source_cam', 'enabled': True, 'value': 'CAM', 'aliases': ['CAM'], 'order': 20},
                           {'id': 'source_ts', 'enabled': True, 'value': 'TS', 'aliases': ['TS'], 'order': 10}],
                'effect': [{'id': 'effect_dv',
                            'enabled': True,
                            'value': 'DV',
                            'aliases': ['DV', 'DoVi', 'Dolby Vision', 'DolbyVision'],
                            'order': 90},
                           {'id': 'effect_hdr10',
                            'enabled': True,
                            'value': 'HDR10',
                            'aliases': ['HDR10', 'HDR10+', 'HDR10P'],
                            'order': 80},
                           {'id': 'effect_hdrvivid',
                            'enabled': True,
                            'value': 'HDR.Vivid',
                            'aliases': ['HDRVivid', 'HDR Vivid', 'HDR.Vivid', 'Vivid'],
                            'order': 75},
                           {'id': 'effect_hdr', 'enabled': True, 'value': 'HDR', 'aliases': ['HDR'], 'order': 70},
                           {'id': 'effect_hlg', 'enabled': True, 'value': 'HLG', 'aliases': ['HLG'], 'order': 60},
                           {'id': 'effect_edr', 'enabled': True, 'value': 'EDR', 'aliases': ['EDR'], 'order': 50},
                           {'id': 'effect_hq', 'enabled': True, 'value': 'HQ', 'aliases': ['HQ'], 'order': 40},
                           {'id': 'effect_sdr', 'enabled': True, 'value': 'SDR', 'aliases': ['SDR'], 'order': 30},
                           {'id': 'effect_3d', 'enabled': True, 'value': '3D', 'aliases': ['3D'], 'order': 20}],
                'webSource': [{'id': 'web_amzn',
                               'enabled': True,
                               'value': 'AMZN',
                               'aliases': ['AMZN', 'Amazon', 'Prime'],
                               'order': 100},
                              {'id': 'web_nf',
                               'enabled': True,
                               'value': 'NF',
                               'aliases': ['NF', 'Netflix'],
                               'order': 99},
                              {'id': 'web_atvp',
                               'enabled': True,
                               'value': 'ATVP',
                               'aliases': ['ATVP', 'AppleTV+', 'Apple TV+', 'AppleTV'],
                               'order': 98},
                              {'id': 'web_it',
                               'enabled': True,
                               'value': 'iT',
                               'aliases': ['iT', 'iTunes'],
                               'order': 97},
                              {'id': 'web_dsnp',
                               'enabled': True,
                               'value': 'DSNP',
                               'aliases': ['DSNP', 'Disney+', 'Disney Plus'],
                               'order': 96},
                              {'id': 'web_hulu', 'enabled': True, 'value': 'Hulu', 'aliases': ['Hulu'], 'order': 95},
                              {'id': 'web_max', 'enabled': True, 'value': 'MAX', 'aliases': ['MAX', 'HMAX'], 'order': 94},
                              {'id': 'web_hbo',
                               'enabled': True,
                               'value': 'HBO',
                               'aliases': ['HBO', 'HBOGO'],
                               'order': 92},
                              {'id': 'web_cr',
                               'enabled': True,
                               'value': 'CR',
                               'aliases': ['CR', 'Crunchyroll'],
                               'order': 91},
                              {'id': 'web_iq', 'enabled': True, 'value': 'IQ', 'aliases': ['IQ', 'iQIYI'], 'order': 90},
                              {'id': 'web_wetv',
                               'enabled': True,
                               'value': 'WeTV',
                               'aliases': ['WeTV', 'Tencent', 'TXTV'],
                               'order': 89},
                              {'id': 'web_bilibili',
                               'enabled': True,
                               'value': 'Bilibili',
                               'aliases': ['Bilibili', 'Bili'],
                               'order': 88},
                              {'id': 'web_bg',
                               'enabled': True,
                               'value': 'BG',
                               'aliases': ['BG', 'B-Global'],
                               'order': 87},
                              {'id': 'web_youku',
                               'enabled': True,
                               'value': 'YOUKU',
                               'aliases': ['YOUKU', 'YK'],
                               'order': 86},
                              {'id': 'web_mgtv', 'enabled': True, 'value': 'MGTV', 'aliases': ['MGTV'], 'order': 85},
                              {'id': 'web_abma',
                               'enabled': True,
                               'value': 'ABMA',
                               'aliases': ['ABEMA', 'ABMA'],
                               'order': 84},
                              {'id': 'web_adn', 'enabled': True, 'value': 'ADN', 'aliases': ['ADN'], 'order': 83},
                              {'id': 'web_atx', 'enabled': True, 'value': 'AT-X', 'aliases': ['AT-X'], 'order': 82},
                              {'id': 'web_baha', 'enabled': True, 'value': 'Baha', 'aliases': ['Baha'], 'order': 81},
                              {'id': 'web_fod', 'enabled': True, 'value': 'FOD', 'aliases': ['FOD'], 'order': 80},
                              {'id': 'web_friDay',
                               'enabled': True,
                               'value': 'FriDay',
                               'aliases': ['FriDay', 'Friday影音'],
                               'order': 79},
                              {'id': 'web_kktv', 'enabled': True, 'value': 'KKTV', 'aliases': ['KKTV'], 'order': 78},
                              {'id': 'web_funi',
                               'enabled': True,
                               'value': 'FUNi',
                               'aliases': ['FUNi', 'Funimation'],
                               'order': 77},
                              {'id': 'web_hidi',
                               'enabled': True,
                               'value': 'HIDI',
                               'aliases': ['HIDI', 'HIDIVE'],
                               'order': 76},
                              {'id': 'web_unxt',
                               'enabled': True,
                               'value': 'UNXT',
                               'aliases': ['UNXT', 'U-Next'],
                               'order': 75},
                              {'id': 'web_viu', 'enabled': True, 'value': 'VIU', 'aliases': ['VIU'], 'order': 74},
                              {'id': 'web_linetv',
                               'enabled': True,
                               'value': 'LINETV',
                               'aliases': ['LINETV'],
                               'order': 73},
                              {'id': 'web_hami',
                               'enabled': True,
                               'value': 'Hami',
                               'aliases': ['Hami', 'HamiVideo', 'Hami Video'],
                               'order': 72},
                              {'id': 'web_mw', 'enabled': True, 'value': 'MW', 'aliases': ['MW'], 'order': 71},
                              {'id': 'web_cpp',
                               'enabled': True,
                               'value': 'CPP',
                               'aliases': ['CPP', 'CATCHPLAY'],
                               'order': 70},
                              {'id': 'web_mytvsuper',
                               'enabled': True,
                               'value': 'myTVSUPER',
                               'aliases': ['myTVSUPER', 'myTV Super'],
                               'order': 69},
                              {'id': 'web_tving', 'enabled': True, 'value': 'TVING', 'aliases': ['TVING'], 'order': 68},
                              {'id': 'web_wavve', 'enabled': True, 'value': 'Wavve', 'aliases': ['Wavve'], 'order': 67},
                              {'id': 'web_yt',
                               'enabled': True,
                               'value': 'YT',
                               'aliases': ['YT', 'YouTube'],
                               'order': 60}],
                'videoCodec': [{'id': 'video_av1', 'enabled': True, 'value': 'AV1', 'aliases': ['AV1'], 'order': 100},
                               {'id': 'video_hevc',
                                'enabled': True,
                                'value': 'HEVC',
                                'aliases': ['HEVC', 'H265', 'H.265', 'x265', 'X.265'],
                                'order': 90},
                               {'id': 'video_avc',
                                'enabled': True,
                                'value': 'AVC',
                                'aliases': ['AVC', 'H264', 'H.264', 'x264', 'X.264'],
                                'order': 80},
                               {'id': 'video_mpeg2',
                                'enabled': True,
                                'value': 'MPEG-2',
                                'aliases': ['MPEG-2', 'MPEG2'],
                                'order': 70},
                               {'id': 'video_vc1',
                                'enabled': True,
                                'value': 'VC-1',
                                'aliases': ['VC-1', 'VC1'],
                                'order': 60}],
                'audioCodec': [{'id': 'audio_truehd',
                                'enabled': True,
                                'value': 'TrueHD',
                                'aliases': ['TrueHD'],
                                'order': 100},
                               {'id': 'audio_ddp',
                                'enabled': True,
                                'value': 'DDP',
                                'aliases': ['DDP', 'EAC3', 'DD+'],
                                'order': 90},
                               {'id': 'audio_dd',
                                'enabled': True,
                                'value': 'DD',
                                'aliases': ['DD', 'AC3'],
                                'order': 80},
                               {'id': 'audio_dts_hd_ma',
                                'enabled': True,
                                'value': 'DTS.HD.MA',
                                'aliases': ['DTS-HD MA', 'DTS HD MA', 'DTS.HD.MA'],
                                'order': 70},
                               {'id': 'audio_dts_hd_hra',
                                'enabled': True,
                                'value': 'DTS.HD.HRA',
                                'aliases': ['DTS-HD HRA', 'DTS HD HRA', 'DTS.HD.HRA'],
                                'order': 65},
                               {'id': 'audio_dtsx',
                                'enabled': True,
                                'value': 'DTS.X',
                                'aliases': ['DTS-X', 'DTS X', 'DTS.X'],
                                'order': 60},
                               {'id': 'audio_dts', 'enabled': True, 'value': 'DTS', 'aliases': ['DTS'], 'order': 55},
                               {'id': 'audio_aac', 'enabled': True, 'value': 'AAC', 'aliases': ['AAC'], 'order': 50},
                               {'id': 'audio_flac', 'enabled': True, 'value': 'FLAC', 'aliases': ['FLAC'], 'order': 45},
                               {'id': 'audio_lpcm',
                                'enabled': True,
                                'value': 'LPCM',
                                'aliases': ['LPCM', 'PCM'],
                                'order': 40},
                               {'id': 'audio_opus',
                                'enabled': True,
                                'value': 'Opus',
                                'aliases': ['Opus'],
                                'order': 35},
                               {'id': 'audio_av3a',
                                'enabled': True,
                                'value': 'AV3A',
                                'aliases': ['AV3A'],
                                'order': 30}],
                'edition': [{'id': 'edition_cc',
                             'enabled': True,
                             'value': 'CC',
                             'aliases': ['CC', 'Criterion', 'Criterion Collection'],
                             'order': 120},
                            {'id': 'edition_directors_cut',
                             'enabled': True,
                             'value': "Director's Cut",
                             'aliases': ["Director's Cut", 'Directors Cut', 'DC'],
                             'order': 119},
                            {'id': 'edition_extended',
                             'enabled': True,
                             'value': 'Extended',
                             'aliases': ['Extended', 'Extended Cut', 'Extended Edition'],
                             'order': 118},
                            {'id': 'edition_theatrical',
                             'enabled': True,
                             'value': 'Theatrical',
                             'aliases': ['Theatrical', 'Theatrical Cut', 'Theatrical Edition'],
                             'order': 117},
                            {'id': 'edition_unrated',
                             'enabled': True,
                             'value': 'Unrated',
                             'aliases': ['Unrated'],
                             'order': 116},
                            {'id': 'edition_open_matte',
                             'enabled': True,
                             'value': 'Open Matte',
                             'aliases': ['Open Matte'],
                             'order': 115},
                            {'id': 'edition_imax',
                             'enabled': True,
                             'value': 'IMAX',
                             'aliases': ['IMAX', 'IMAX Enhanced'],
                             'order': 114},
                            {'id': 'edition_hybrid',
                             'enabled': True,
                             'value': 'Hybrid',
                             'aliases': ['Hybrid'],
                             'order': 113},
                            {'id': 'edition_remastered',
                             'enabled': True,
                             'value': 'Remastered',
                             'aliases': ['Remastered', 'Restored'],
                             'order': 112},
                            {'id': 'edition_anniversary',
                             'enabled': True,
                             'value': 'Anniversary Edition',
                             'aliases': ['Anniversary Edition'],
                             'order': 111},
                            {'id': 'edition_collectors',
                             'enabled': True,
                             'value': "Collector's Edition",
                             'aliases': ["Collector's Edition", 'Collectors Edition'],
                             'order': 110},
                            {'id': 'edition_ultimate',
                             'enabled': True,
                             'value': 'Ultimate Edition',
                             'aliases': ['Ultimate Edition'],
                             'order': 109},
                            {'id': 'edition_proper',
                             'enabled': True,
                             'value': 'PROPER',
                             'aliases': ['PROPER'],
                             'order': 108},
                            {'id': 'edition_repack',
                             'enabled': True,
                             'value': 'REPACK',
                             'aliases': ['REPACK'],
                             'order': 107},
                            {'id': 'edition_rerip',
                             'enabled': True,
                             'value': 'RERIP',
                             'aliases': ['RERIP'],
                             'order': 106},
                            {'id': 'edition_maxplus',
                             'enabled': True,
                             'value': 'MAXPLUS',
                             'aliases': ['MAXPLUS'],
                             'order': 105},
                            {'id': 'edition_ger',
                             'enabled': True,
                             'value': 'GER',
                             'aliases': ['GER', 'DEU'],
                             'order': 90},
                            {'id': 'edition_jpn', 'enabled': True, 'value': 'JPN', 'aliases': ['JPN'], 'order': 89},
                            {'id': 'edition_usa', 'enabled': True, 'value': 'USA', 'aliases': ['USA'], 'order': 88},
                            {'id': 'edition_fra',
                             'enabled': True,
                             'value': 'FRA',
                             'aliases': ['FRA', 'FRE'],
                             'order': 87},
                            {'id': 'edition_ita', 'enabled': True, 'value': 'ITA', 'aliases': ['ITA'], 'order': 86},
                            {'id': 'edition_esp',
                             'enabled': True,
                             'value': 'ESP',
                             'aliases': ['ESP', 'SPA'],
                             'order': 85},
                            {'id': 'edition_kor', 'enabled': True, 'value': 'KOR', 'aliases': ['KOR'], 'order': 84},
                            {'id': 'edition_hk', 'enabled': True, 'value': 'HK', 'aliases': ['HK'], 'order': 83},
                            {'id': 'edition_tw', 'enabled': True, 'value': 'TW', 'aliases': ['TW'], 'order': 82},
                            {'id': 'edition_uk', 'enabled': True, 'value': 'UK', 'aliases': ['UK', 'GBR'], 'order': 81},
                            {'id': 'edition_eur', 'enabled': True, 'value': 'EUR', 'aliases': ['EUR'], 'order': 80},
                            {'id': 'edition_can', 'enabled': True, 'value': 'CAN', 'aliases': ['CAN'], 'order': 79},
                            {'id': 'edition_aus', 'enabled': True, 'value': 'AUS', 'aliases': ['AUS'], 'order': 78},
                            {'id': 'edition_nld',
                             'enabled': True,
                             'value': 'NLD',
                             'aliases': ['NLD', 'DUT'],
                             'order': 77},
                            {'id': 'edition_swe', 'enabled': True, 'value': 'SWE', 'aliases': ['SWE'], 'order': 76},
                            {'id': 'edition_nor', 'enabled': True, 'value': 'NOR', 'aliases': ['NOR'], 'order': 75},
                            {'id': 'edition_fin', 'enabled': True, 'value': 'FIN', 'aliases': ['FIN'], 'order': 74},
                            {'id': 'edition_dnk',
                             'enabled': True,
                             'value': 'DNK',
                             'aliases': ['DNK', 'DAN'],
                             'order': 73},
                            {'id': 'edition_pol', 'enabled': True, 'value': 'POL', 'aliases': ['POL'], 'order': 72},
                            {'id': 'edition_rus', 'enabled': True, 'value': 'RUS', 'aliases': ['RUS'], 'order': 71},
                            {'id': 'edition_chn', 'enabled': True, 'value': 'CHN', 'aliases': ['CHN'], 'order': 70},
                            {'id': 'edition_tha', 'enabled': True, 'value': 'THA', 'aliases': ['THA'], 'order': 69},
                            {'id': 'edition_ind', 'enabled': True, 'value': 'IND', 'aliases': ['IND'], 'order': 68},
                            {'id': 'edition_mex', 'enabled': True, 'value': 'MEX', 'aliases': ['MEX'], 'order': 67},
                            {'id': 'edition_bra', 'enabled': True, 'value': 'BRA', 'aliases': ['BRA'], 'order': 66}],
                'recognition': {'excludeWords': [],
                                'replacements': [],
                                'movieKeywords': ['movie', '电影', '影片', '🎬'],
                                'tvKeywords': ['tv', '剧集', '电视剧', '连续剧', '番剧', '📺'],
                                'releaseGroups': ['Mo Cuishle']},
                'display': {'sourceLabels': [{'id': 'display_uhd_bluray_remux',
                                              'enabled': True,
                                              'source': 'UHD BluRay Remux',
                                              'template': '{{resolution4k}}蓝光原盘REMUX',
                                              'order': 100},
                                             {'id': 'display_bluray_remux',
                                              'enabled': True,
                                              'source': 'BluRay Remux',
                                              'template': '{{resolution}}蓝光原盘REMUX',
                                              'order': 90},
                                             {'id': 'display_uhd_bluray',
                                              'enabled': True,
                                              'source': 'UHD BluRay',
                                              'template': '{{resolution4k}}蓝光原盘压制',
                                              'order': 80},
                                             {'id': 'display_bluray',
                                              'enabled': True,
                                              'source': 'BluRay',
                                              'template': '{{resolution}}蓝光原盘压制',
                                              'order': 70},
                                             {'id': 'display_uhdtv',
                                              'enabled': True,
                                              'source': 'UHDTV',
                                              'template': '{{resolution4k}} UHDTV',
                                              'order': 60}]}},
 'templates': {'shareName': '123',
               'shareUrl': '',
               'caption': '🎬 <b>{title}</b>\n'
                          '\n'
                          '{tmdbMarker}\n'
                          '⭐ TMDB评分：{tmdbRating}\n'
                          '🍿 豆瓣评分：{doubanRating}\n'
                          '🖥️ 画质：{quality}\n'
                          '💽 视频：{source}\n'
                          '💾 大小：{size}\n'
                          '📣 路由：{routeChannel}\n'
                          '👤 分享：{shareLink}\n'
                          '{resourceBlock}\n'
                          '\n'
                          '{overviewBlock}\n'
                          '\n'
                          '🏷 标签：{tags}'}}
DEFAULT_SUBMISSION_CONFIG.setdefault("pan115Helper", {
    "enabled": False,
    "pan115Cookie": "",
    "offlineTargetDirId": "0",
    "trashPassword": "",
    "dailyRecycleCleanupEnabled": False,
    "dailyRecycleCleanupTime": "03:30",
    "dailyRecycleCleanupTimeZone": "Asia/Shanghai",
    "requestIntervalMs": 2500,
})
DEFAULT_SUBMISSION_CONFIG.setdefault("telegramAdminUserIds", [])
DEFAULT_SUBMISSION_CONFIG.setdefault("channelOwnerUserIds", [])

# --- 用户级频道配置默认值 ---

DEFAULT_USER_CHANNELS = [
    {"id": "private", "title": "私有", "chatId": "", "enabled": True, "isDefault": True, "role": "private", "allowedUserIds": []},
]

DEFAULT_USER_ROUTING = {
    "publicReleaseGroups": [],
    "releaseGroupChannelId": "private",
    "noReleaseGroupCompletedChannelId": "",
    "noReleaseGroupUpdatingChannelId": "",
    "fallbackChannelId": "",
}
