import { h, type Component, type DefineComponent } from "vue";
import { VSvgIcon } from "vuetify/components";
import { aliases as mdiAliases } from "vuetify/iconsets/mdi-svg";
import {
  mdiAccountCircleOutline, mdiAccountMultipleOutline, mdiAccountOutline, mdiAccountSupervisorOutline,
  mdiAlert, mdiAlertCircle, mdiAlertCircleOutline, mdiApi, mdiArrowDown, mdiArrowUp, mdiBlur, mdiBrain,
  mdiBrightness4, mdiBrightness7, mdiBroadcast, mdiBroom, mdiChartLine, mdiCheckCircle,
  mdiCheckCircleOutline, mdiCheckDecagram, mdiChevronDown, mdiChevronRight, mdiChevronUp, mdiCircleOutline,
  mdiClipboardCheckOutline, mdiClipboardListOutline, mdiClock, mdiClockOutline, mdiClose, mdiCloudKey,
  mdiCloudKeyOutline, mdiCloudSync, mdiCloudUploadOutline, mdiCodeTags, mdiCog, mdiCogOutline, mdiConnection,
  mdiContentCopy, mdiContentSave, mdiCookie, mdiCounter, mdiCursorMove, mdiDatabaseSearch, mdiDelete,
  mdiDeleteOutline, mdiDisc, mdiDotsHorizontal, mdiEyeOffOutline, mdiEyeOutline, mdiFileCheck,
  mdiFileDocumentEditOutline, mdiFileDocumentMultiple, mdiFileDocumentMultipleOutline, mdiFileDocumentOutline,
  mdiFileEditOutline, mdiFileMultiple, mdiFileMultipleOutline, mdiFileRemove, mdiFileTree, mdiFilterRemoveOutline, mdiFlagVariantOutline,
  mdiFlaskOutline, mdiFolder, mdiFolderCogOutline, mdiFolderEditOutline, mdiFolderHeart, mdiFolderMultiple,
  mdiFolderMultipleImage, mdiFolderMultipleOutline, mdiFolderStarOutline, mdiFormatListBulleted,
  mdiFormatListBulletedType, mdiFormatListChecks, mdiGauge, mdiGradientHorizontal, mdiHelpCircleOutline,
  mdiHistory, mdiImageSizeSelectLarge, mdiInboxOutline, mdiInformation, mdiInformationOutline, mdiKeyVariant,
  mdiKeyboardOutline, mdiLanConnect, mdiLightningBolt, mdiLockOutline, mdiLogin, mdiLogout, mdiMagnify,
  mdiMenu, mdiMovie, mdiNetflix, mdiPackageVariantClosed, mdiPalette, mdiPencil, mdiPencilOutline,
  mdiPencilRuler, mdiPlus, mdiProgressClock, mdiQrcodeScan, mdiRefresh, mdiRegex, mdiRenameBox, mdiRobot,
  mdiRoutes, mdiSend, mdiShapeOutline, mdiShareVariant, mdiShieldAccountOutline, mdiShieldLockOutline,
  mdiShieldOutline, mdiSortVariant, mdiStar, mdiStarBoxOutline, mdiStarOffOutline, mdiStarOutline,
  mdiTagMultiple, mdiTagMultipleOutline, mdiTagRemove, mdiTagTextOutline, mdiThemeLightDark, mdiTimerCog,
  mdiTools, mdiTrashCanOutline, mdiTrendingDown, mdiTrendingUp, mdiTruck, mdiVideo, mdiViewDashboardOutline,
  mdiVolumeHigh, mdiWeatherNight, mdiWhiteBalanceSunny,
  mdiAccount, mdiAccountSwitchOutline, mdiCellphoneArrowDown, mdiChevronLeft, mdiCloudCheckOutline, mdiCloudSyncOutline, mdiConsole, mdiConsoleLine, mdiDatabaseOutline, mdiDockLeft, mdiFileHidden, mdiFlash, mdiFolderArrowRightOutline, mdiFolderOpenOutline, mdiLan, mdiLinkVariant, mdiLinkVariantOff, mdiMoonWaningCrescent, mdiOpenInNew, mdiPause, mdiPlay, mdiProgressDownload, mdiReload, mdiRestart, mdiServer, mdiTextBoxOutline, mdiTimerCogOutline, mdiTruckFast, mdiTuneVariant,
} from "@mdi/js";

const iconPaths: Record<string, string> = {
  "mdi-account-circle-outline": mdiAccountCircleOutline,
  "mdi-account-multiple-outline": mdiAccountMultipleOutline,
  "mdi-account-outline": mdiAccountOutline,
  "mdi-account-supervisor-outline": mdiAccountSupervisorOutline,
  "mdi-alert": mdiAlert,
  "mdi-alert-circle": mdiAlertCircle,
  "mdi-alert-circle-outline": mdiAlertCircleOutline,
  "mdi-api": mdiApi,
  "mdi-arrow-down": mdiArrowDown,
  "mdi-arrow-up": mdiArrowUp,
  "mdi-blur": mdiBlur,
  "mdi-brain": mdiBrain,
  "mdi-brightness-4": mdiBrightness4,
  "mdi-brightness-7": mdiBrightness7,
  "mdi-broadcast": mdiBroadcast,
  "mdi-broom": mdiBroom,
  "mdi-chart-line": mdiChartLine,
  "mdi-check-circle": mdiCheckCircle,
  "mdi-check-circle-outline": mdiCheckCircleOutline,
  "mdi-check-decagram": mdiCheckDecagram,
  "mdi-chevron-down": mdiChevronDown,
  "mdi-chevron-right": mdiChevronRight,
  "mdi-chevron-up": mdiChevronUp,
  "mdi-circle-outline": mdiCircleOutline,
  "mdi-clipboard-list-outline": mdiClipboardListOutline,
  "mdi-clock": mdiClock,
  "mdi-clock-outline": mdiClockOutline,
  "mdi-close": mdiClose,
  "mdi-cloud-key": mdiCloudKey,
  "mdi-cloud-key-outline": mdiCloudKeyOutline,
  "mdi-cloud-sync": mdiCloudSync,
  "mdi-cloud-upload-outline": mdiCloudUploadOutline,
  "mdi-code-tags": mdiCodeTags,
  "mdi-cog": mdiCog,
  "mdi-cog-outline": mdiCogOutline,
  "mdi-connection": mdiConnection,
  "mdi-content-copy": mdiContentCopy,
  "mdi-content-save": mdiContentSave,
  "mdi-cookie": mdiCookie,
  "mdi-counter": mdiCounter,
  "mdi-database-search": mdiDatabaseSearch,
  "mdi-delete": mdiDelete,
  "mdi-delete-outline": mdiDeleteOutline,
  "mdi-disc": mdiDisc,
  "mdi-dots-horizontal": mdiDotsHorizontal,
  "mdi-eye-off-outline": mdiEyeOffOutline,
  "mdi-eye-outline": mdiEyeOutline,
  "mdi-file-check": mdiFileCheck,
  "mdi-file-document-edit-outline": mdiFileDocumentEditOutline,
  "mdi-file-document-multiple": mdiFileDocumentMultiple,
  "mdi-file-document-multiple-outline": mdiFileDocumentMultipleOutline,
  "mdi-file-document-outline": mdiFileDocumentOutline,
  "mdi-file-edit-outline": mdiFileEditOutline,
  "mdi-file-multiple": mdiFileMultiple,
  "mdi-file-multiple-outline": mdiFileMultipleOutline,
  "mdi-file-remove": mdiFileRemove,
  "mdi-file-tree": mdiFileTree,
  "mdi-filter-remove-outline": mdiFilterRemoveOutline,
  "mdi-flag-variant-outline": mdiFlagVariantOutline,
  "mdi-flask-outline": mdiFlaskOutline,
  "mdi-folder": mdiFolder,
  "mdi-folder-cog-outline": mdiFolderCogOutline,
  "mdi-folder-edit-outline": mdiFolderEditOutline,
  "mdi-folder-heart": mdiFolderHeart,
  "mdi-folder-multiple": mdiFolderMultiple,
  "mdi-folder-multiple-media": mdiFolderMultipleImage,
  "mdi-folder-multiple-outline": mdiFolderMultipleOutline,
  "mdi-folder-star-outline": mdiFolderStarOutline,
  "mdi-format-list-bulleted": mdiFormatListBulleted,
  "mdi-format-list-bulleted-type": mdiFormatListBulletedType,
  "mdi-format-list-checks": mdiFormatListChecks,
  "mdi-gauge": mdiGauge,
  "mdi-gradient-horizontal": mdiGradientHorizontal,
  "mdi-help-circle-outline": mdiHelpCircleOutline,
  "mdi-history": mdiHistory,
  "mdi-inbox-outline": mdiInboxOutline,
  "mdi-information": mdiInformation,
  "mdi-information-outline": mdiInformationOutline,
  "mdi-key-variant": mdiKeyVariant,
  "mdi-keyboard-outline": mdiKeyboardOutline,
  "mdi-lan-connect": mdiLanConnect,
  "mdi-lightning-bolt": mdiLightningBolt,
  "mdi-lock-outline": mdiLockOutline,
  "mdi-login": mdiLogin,
  "mdi-logout": mdiLogout,
  "mdi-magnify": mdiMagnify,
  "mdi-menu": mdiMenu,
  "mdi-move": mdiCursorMove,
  "mdi-movie": mdiMovie,
  "mdi-netflix": mdiNetflix,
  "mdi-package-variant-closed": mdiPackageVariantClosed,
  "mdi-palette": mdiPalette,
  "mdi-pencil": mdiPencil,
  "mdi-pencil-outline": mdiPencilOutline,
  "mdi-pencil-ruler": mdiPencilRuler,
  "mdi-plus": mdiPlus,
  "mdi-progress-clock": mdiProgressClock,
  "mdi-qrcode-scan": mdiQrcodeScan,
  "mdi-refresh": mdiRefresh,
  "mdi-regex": mdiRegex,
  "mdi-rename-box": mdiRenameBox,
  "mdi-resolution": mdiImageSizeSelectLarge,
  "mdi-robot": mdiRobot,
  "mdi-routes-outline": mdiRoutes,
  "mdi-send": mdiSend,
  "mdi-shape-outline": mdiShapeOutline,
  "mdi-share-variant": mdiShareVariant,
  "mdi-shield-account-outline": mdiShieldAccountOutline,
  "mdi-shield-lock-outline": mdiShieldLockOutline,
  "mdi-shield-outline": mdiShieldOutline,
  "mdi-sort-variant": mdiSortVariant,
  "mdi-star": mdiStar,
  "mdi-star-box-outline": mdiStarBoxOutline,
  "mdi-star-off-outline": mdiStarOffOutline,
  "mdi-star-outline": mdiStarOutline,
  "mdi-tag-multiple": mdiTagMultiple,
  "mdi-tag-multiple-outline": mdiTagMultipleOutline,
  "mdi-tag-remove": mdiTagRemove,
  "mdi-tag-text-outline": mdiTagTextOutline,
  "mdi-task": mdiClipboardCheckOutline,
  "mdi-theme-light-dark": mdiThemeLightDark,
  "mdi-timer-cog": mdiTimerCog,
  "mdi-tools": mdiTools,
  "mdi-trash-can-outline": mdiTrashCanOutline,
  "mdi-trending-down": mdiTrendingDown,
  "mdi-trending-up": mdiTrendingUp,
  "mdi-truck": mdiTruck,
  "mdi-video": mdiVideo,
  "mdi-view-dashboard-outline": mdiViewDashboardOutline,
  "mdi-volume-high": mdiVolumeHigh,
  "mdi-weather-night": mdiWeatherNight,
  "mdi-white-balance-sunny": mdiWhiteBalanceSunny,
  "mdi-account": mdiAccount,
  "mdi-account-switch-outline": mdiAccountSwitchOutline,
  "mdi-cellphone-arrow-down": mdiCellphoneArrowDown,
  "mdi-chevron-left": mdiChevronLeft,
  "mdi-cloud-check-outline": mdiCloudCheckOutline,
  "mdi-cloud-sync-outline": mdiCloudSyncOutline,
  "mdi-console": mdiConsole,
  "mdi-console-line": mdiConsoleLine,
  "mdi-database-outline": mdiDatabaseOutline,
  "mdi-dock-left": mdiDockLeft,
  "mdi-file-hidden": mdiFileHidden,
  "mdi-flash": mdiFlash,
  "mdi-folder-arrow-right-outline": mdiFolderArrowRightOutline,
  "mdi-folder-open-outline": mdiFolderOpenOutline,
  "mdi-lan": mdiLan,
  "mdi-link-variant": mdiLinkVariant,
  "mdi-link-variant-off": mdiLinkVariantOff,
  "mdi-moon-waning-crescent": mdiMoonWaningCrescent,
  "mdi-open-in-new": mdiOpenInNew,
  "mdi-pause": mdiPause,
  "mdi-play": mdiPlay,
  "mdi-progress-download": mdiProgressDownload,
  "mdi-reload": mdiReload,
  "mdi-restart": mdiRestart,
  "mdi-routes": mdiRoutes,
  "mdi-server": mdiServer,
  "mdi-text-box-outline": mdiTextBoxOutline,
  "mdi-timer-cog-outline": mdiTimerCogOutline,
  "mdi-truck-fast": mdiTruckFast,
  "mdi-tune-variant": mdiTuneVariant,
  "mdi-zap": mdiLightningBolt,
};

const mdiSvg: Component = (props: { icon?: string }) => {
  const icon = String(props.icon || "");
  return h(
    VSvgIcon as unknown as DefineComponent,
    { ...props, icon: icon.startsWith("svg:") ? icon.slice(4) : (iconPaths[icon] || mdiHelpCircleOutline) }
  );
};

export const appIcons = {
  defaultSet: "app",
  aliases: mdiAliases,
  sets: { app: { component: mdiSvg } },
};
